apiVersion: v1
kind: Service
metadata:
  name: service-node-kafka
  namespace: test-kafka
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: kafka-producer
  type: LoadBalancer
